<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Thu, 17 Mar 2016 13:28:47 +0000
 */
$conf['title'] = 'Documentacion odoo';
$conf['lang'] = 'es';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
